# Generated by Django 4.0.5 on 2022-06-24 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_service', to='hack.business', verbose_name='бизнес/деятельность')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='телефон')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='город')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='почта')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='hack.business', verbose_name='бизнес/деятельность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_index=True, max_length=100, verbose_name='событие')),
                ('datetime', models.DateTimeField(verbose_name='дата')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_plan', to='hack.business', verbose_name='бизнес/деятельность')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='hack.service', verbose_name='услуга')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('date', models.DateField(verbose_name='дата')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_expense', to='hack.business', verbose_name='бизнес/деятельность')),
            ],
        ),
    ]
